steps:
  - label: "Nvidia GPUs -- MRIReco.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
    agents:
      queue: "juliagpu"
      cuda: "*"
    command: |
      julia --color=yes --project -e '
      using Pkg
      Pkg.add(PackageSpec(path=pwd(), subdir="MRIBase"))
      Pkg.add(PackageSpec(path=pwd(), subdir="MRIFiles"))
      Pkg.add(PackageSpec(path=pwd(), subdir="MRISampling"))
      Pkg.add(PackageSpec(path=pwd(), subdir="MRISimulation"))
      Pkg.add(PackageSpec(path=pwd(), subdir="MRIOperators"))
      Pkg.add(PackageSpec(path=pwd(), subdir="MRICoilSensitivities"))
      Pkg.add("TestEnv")
      using TestEnv
      TestEnv.activate();
      Pkg.add("CUDA")
      Pkg.instantiate()
      include("test/gpu/cuda.jl")'
    timeout_in_minutes: 30

  - label: "Nvidia GPUs -- MRIOperators.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
    agents:
      queue: "juliagpu"
      cuda: "*"
    command: |
      julia --color=yes --project -e '
      using Pkg
      Pkg.add(PackageSpec(path=pwd(), subdir="MRIBase"))
      Pkg.add(PackageSpec(path=pwd(), subdir="MRIFiles"))
      Pkg.add(PackageSpec(path=pwd(), subdir="MRISampling"))
      Pkg.add(PackageSpec(path=pwd(), subdir="MRISimulation"))
      Pkg.add(PackageSpec(path=pwd(), subdir="MRIOperators"))
      Pkg.add(PackageSpec(path=pwd(), subdir="MRICoilSensitivities"))
      Pkg.add("TestEnv")
      using TestEnv
      TestEnv.activate();
      Pkg.add("CUDA")
      Pkg.instantiate()
      include("MRIOperators/test/gpu/cuda.jl")'
    timeout_in_minutes: 30


  #label: "AMD GPUs -- MRIOperators.jl"
  #plugins:
  #  - JuliaCI/julia#v1:
  #      version: "1.10"
  #agents:
  #  queue: "juliagpu"
  #  rocm: "*"
  #  rocmgpu: "*"
  #command: |
  #  julia --color=yes --project -e '
  #  using Pkg
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRIBase"))
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRIFiles"))
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRISampling"))
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRISimulation"))
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRIOperators"))
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRICoilSensitivities"))
  #  Pkg.add("TestEnv")
  #  using TestEnv
  #  TestEnv.activate();
  #  Pkg.add("AMDGPU")
  #  Pkg.instantiate()
  #  include("MRIOperators/test/gpu/rocm.jl")'
  #timeout_in_minutes: 30
#
  #label: "AMD GPUs -- MRIReco.jl"
  #plugins:
  #  - JuliaCI/julia#v1:
  #      version: "1.10"
  #agents:
  #  queue: "juliagpu"
  #  rocm: "*"
  #  rocmgpu: "*"
  #command: |
  #  julia --color=yes --project -e '
  #  using Pkg
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRIBase"))
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRIFiles"))
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRISampling"))
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRISimulation"))
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRIOperators"))
  #  Pkg.add(PackageSpec(path=pwd(), subdir="MRICoilSensitivities"))
  #  Pkg.add("TestEnv")
  #  using TestEnv
  #  TestEnv.activate();
  #  Pkg.add("AMDGPU")
  #  Pkg.instantiate()
  #  include("test/gpu/rocm.jl")'
  #timeout_in_minutes: 30